# Generated by Django 4.1.3 on 2022-11-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0002_rename_status_user_about_rename_image_user_avatar_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="user_avatars/"),
        ),
    ]
