# Generated by Django 4.1.3 on 2022-11-29 20:04

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["-id"]},
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="is_single",
            new_name="single",
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="complexity",
            field=models.CharField(
                choices=[("EASY", "Easy"), ("MEDIUM", "Medium"), ("HARD", "Hard")],
                default=None,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="cost",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[("ONLINE", "Online"), ("VIDEO", "Video")],
                default=None,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="level",
            field=models.CharField(
                choices=[
                    ("STARTING", "Starting"),
                    ("CONTINUER", "Continuer"),
                    ("ADVANCED", "Advanced"),
                ],
                default=None,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.CharField(
                choices=[
                    ("PAYMENT", "Payment"),
                    ("DONATION", "Donation"),
                    ("FREE", "Free"),
                ],
                default=0,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
