# Generated by Django 4.1.3 on 2022-11-29 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_comment_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="duration",
        ),
    ]
