# Generated by Django 4.1.4 on 2022-12-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "lessons",
            "0010_remove_comment_updated_at_comment_polymorphic_ctype_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="lesson",
        ),
        migrations.CreateModel(
            name="LessonComment",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessons.comment",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий к уроку",
                "verbose_name_plural": "Комментарии к уроку",
            },
            bases=("lessons.comment",),
        ),
    ]
