# Generated by Django 4.1.4 on 2022-12-20 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0013_review_created_at_review_updated_at_alter_review_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="weekday",
        ),
        migrations.AddField(
            model_name="schedule",
            name="start_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
