# Generated by Django 4.1.5 on 2023-01-21 07:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "rating",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0.0),
                            django.core.validators.MaxValueValidator(limit_value=5.0),
                        ],
                    ),
                ),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("published", models.BooleanField(default=False)),
                ("seo_keywords", models.CharField(blank=True, max_length=255)),
                ("seo_description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-created_at"],
            },
        ),
    ]
