# Generated by Django 4.1.5 on 2023-01-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default="sluggg"),
            preserve_default=False,
        ),
    ]
