# Generated by Django 4.1.5 on 2023-01-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_rename_is_draft_article_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="seo_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="seo_keywords",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="articles.tag"
            ),
        ),
    ]
