# Generated by Django 4.1.5 on 2023-01-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_category_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
