# Generated by Django 4.1.5 on 2023-01-22 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tickets",
                to="courses.course",
                verbose_name="Курс",
            ),
        ),
        migrations.CreateModel(
            name="LessonEnrolledUser",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.lesson"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание курса пользователя",
                "verbose_name_plural": "Расписания курсов пользователя",
                "unique_together": {("lesson", "user")},
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="enrolled_users",
            field=models.ManyToManyField(
                related_name="enrolled_users_set",
                through="courses.LessonEnrolledUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Зарегистрированные пользователи",
            ),
        ),
    ]
