# Generated by Django 4.1.3 on 2022-11-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_remove_lesson_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.DurationField(default=None),
            preserve_default=False,
        ),
    ]
