# Generated by Django 4.1.4 on 2022-12-27 12:14

from django.db import migrations, models

import core.app.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0003_ticket_created_at_ticket_updated_at_alter_ticket_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="schedule",
            field=core.app.utils.fields.JSONParsedField(default=list),
        ),
        migrations.AddField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("CANCELED", "Canceled")],
                default="ACTIVE",
                max_length=30,
            ),
        ),
    ]
