# Generated by Django 4.1.5 on 2023-02-04 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0004_remove_review_star_rating_lessonratingstar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lessonratingstar",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lessonratingstar",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="lessonratingstar",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lessonratingstar",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_rating_stars",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
