# Generated by Django 4.1.5 on 2023-02-08 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_basecourse_lesson_participants_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecourse",
            name="lesson_participants_limit",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(limit_value=1)],
                verbose_name="Лимит количества участников онлайн-урока",
            ),
        ),
    ]
