# Generated by Django 4.1.5 on 2023-02-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_remove_lessonratingstar_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Архивирован"),
        ),
    ]
