# Generated by Django 4.1.3 on 2022-12-03 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0005_alter_lesson_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="deadline_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="link",
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="link_info",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="payment",
            field=models.CharField(
                choices=[
                    ("PAYMENT", "Payment"),
                    ("DONATION", "Donation"),
                    ("FREE", "Free"),
                ],
                default=None,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="lesson",
            name="repeat_editing",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="price",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(limit_value=0)]
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=40,
                    ),
                ),
                ("start_time", models.TimeField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
    ]
