# Generated by Django 4.1.4 on 2022-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_coursecycle"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coursecycle",
            old_name="skip_lessons_amount",
            new_name="canceled_lessons_amount",
        ),
        migrations.AddField(
            model_name="course",
            name="rate",
            field=models.IntegerField(default=5),
        ),
    ]
