# Generated by Django 4.1.6 on 2023-02-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_basecourse_lesson_participants_limit"),
        ("courses", "0006_course_archived"),
    ]

    operations = []
