# Generated by Django 4.1.5 on 2023-02-08 07:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0006_course_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonComplaint",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("decision", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPLAINT1", "Complaint1"),
                            ("COMPLAINT2", "Complaint2"),
                        ],
                        max_length=30,
                        verbose_name="Категория жалобы",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жалоба на занятие",
                "verbose_name_plural": "Жалобы по занятиям",
            },
        ),
        migrations.CreateModel(
            name="ComplaintDecision",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                ("decision", models.TextField(verbose_name="Содержание")),
                ("feedback", models.BooleanField(default=True)),
                (
                    "decision_rate",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=1),
                            django.core.validators.MaxValueValidator(limit_value=5),
                        ],
                        verbose_name="Оценка решения",
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.lessoncomplaint",
                        verbose_name="жалоба",
                    ),
                ),
            ],
            options={
                "verbose_name": "Решение на жалобу",
                "verbose_name_plural": "Решения по жалобам",
            },
        ),
    ]
