# Generated by Django 4.1.6 on 2023-02-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_lessoncomplaint_complaintdecision"),
        ("courses", "0007_merge_20230208_1659"),
    ]

    operations = []
