# Generated by Django 4.1.4 on 2022-12-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lessons_set",
                to="courses.course",
            ),
        ),
    ]
