# Generated by Django 4.1.4 on 2022-12-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_alter_course_level_alter_lesson_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="rate",
        ),
    ]
