# Generated by Django 4.1.4 on 2022-12-29 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0010_remove_course_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="complexity",
        ),
        migrations.RemoveField(
            model_name="course",
            name="course_type",
        ),
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="favorites",
        ),
        migrations.RemoveField(
            model_name="course",
            name="level",
        ),
        migrations.RemoveField(
            model_name="course",
            name="name",
        ),
        migrations.RemoveField(
            model_name="course",
            name="repeat_editing",
        ),
        migrations.RemoveField(
            model_name="course",
            name="single",
        ),
        migrations.RemoveField(
            model_name="course",
            name="teacher",
        ),
        migrations.CreateModel(
            name="BaseCourse",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                (
                    "course_type",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("VIDEO", "Video")],
                        max_length=30,
                    ),
                ),
                ("level", models.JSONField()),
                (
                    "complexity",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "favorites",
                    models.ManyToManyField(
                        blank=True,
                        related_name="favorite_courses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="course",
            name="base_course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="courses.basecourse",
            ),
            preserve_default=False,
        ),
    ]
