# Generated by Django 4.1.4 on 2022-12-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_remove_course_complexity_remove_course_course_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("CANCELED", "Canceled"),
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("COMPLETED", "Completed"),
                ],
                default="DRAFT",
                max_length=40,
            ),
            preserve_default=False,
        ),
    ]
