# Generated by Django 4.1.4 on 2022-12-30 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_course_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecomment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="coursereview",
            name="course",
        ),
        migrations.AddField(
            model_name="coursecomment",
            name="base_course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="courses.basecourse",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coursereview",
            name="base_course",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="courses.basecourse",
            ),
            preserve_default=False,
        ),
    ]
