# Generated by Django 4.1.5 on 2023-01-14 11:50

from django.db import migrations

import core.app.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_alter_course_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="schedule",
            field=core.app.utils.fields.JSONParsedField(blank=True, default=list),
        ),
    ]
