# Generated by Django 4.1.5 on 2023-02-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="register_confirm_token",
        ),
        migrations.AddField(
            model_name="user",
            name="register_confirm_code",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="register confirm code",
            ),
        ),
    ]
