# Generated by Django 4.1.5 on 2023-02-02 20:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBillingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=255)),
                ("bic", models.CharField(max_length=11)),
                ("bank", models.CharField(max_length=255)),
                ("organization_address", models.CharField(max_length=255)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(default="RU", max_length=10),
        ),
        migrations.CreateModel(
            name="UserBillingInfoRU",
            fields=[
                (
                    "userbillinginfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.userbillinginfo",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "correspondent_account",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{20}$")
                        ],
                        verbose_name="Корреспондентский счет",
                    ),
                ),
                (
                    "prc",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                        verbose_name="КПП",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="Номер счета"),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.userbillinginfo",),
        ),
        migrations.AddField(
            model_name="userbillinginfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
