# Generated by Django 4.1.3 on 2022-11-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_instructor",
            field=models.BooleanField(default=False),
        ),
    ]
