# Generated by Django 4.1.5 on 2023-02-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_register_confirm_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="register_confirm_code",
            field=models.CharField(
                blank=True,
                max_length=6,
                null=True,
                verbose_name="register confirm code",
            ),
        ),
    ]
