# Generated by Django 4.1.3 on 2022-11-22 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_is_instructor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_instructor",
            new_name="is_teacher",
        ),
    ]
