# Generated by Django 4.1.4 on 2022-12-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_transaction_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_id",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
