# Generated by Django 4.1.5 on 2023-02-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_register_confirm_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="register_confirm_code",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="register confirm code",
            ),
        ),
    ]
