# Generated by Django 4.1.5 on 2023-02-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_user_rate"),
        ("core", "0003_remove_questionnaireteacher_status_and_more"),
    ]

    operations = []
