# Generated by Django 4.1.3 on 2022-11-30 20:39

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_is_instructor_user_is_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.JSONField(default=core.models.user_default_roles),
        ),
    ]
