# Generated by Django 4.1.3 on 2022-12-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_roles"),
    ]


    operations = [
        migrations.AddField(
            model_name="user",
            name="pwd_reset_token",
            field=models.CharField(
                default="test", max_length=300, verbose_name="pwd reset token"
            ),
            preserve_default=False,
        ),
    ]
