# Generated by Django 4.1.5 on 2023-02-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_merge_20230205_0744"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="region",
        ),
    ]
