# Generated by Django 4.1.4 on 2022-12-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_transaction_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIAL", "Initial"),
                    ("CONFIRMED", "Confirmed"),
                    ("DECLINED", "Declined"),
                ],
                default="INITIAL",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
