# Generated by Django 4.1.4 on 2022-12-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_user_pwd_reset_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
