# Generated by Django 4.1.5 on 2023-02-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_user_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("", "Empty")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="hide_birthday",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="questionnaireteacher",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female"), ("", "Empty")],
                max_length=10,
                null=True,
                verbose_name="Пол",
            ),
        ),
    ]
