# Generated by Django 4.1.4 on 2022-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_alter_comment_options_alter_lesson_options_and_more"),
        ("core", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="lessons.lesson"
            ),
        ),
    ]
