# Generated by Django 4.1.5 on 2023-02-05 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_birthday_user_gender_user_hide_birthday_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sys_rate",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
