# Generated by Django 4.1.4 on 2022-12-11 09:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("payment_id", models.CharField(max_length=40)),
            ],
            options={
                "ordering": ["-id"],
                "abstract": False,
            },
        ),
    ]
