# Generated by Django 4.1.4 on 2022-12-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_first_name_alter_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaireteacher",
            name="certificate_photos",
            field=models.ManyToManyField(blank=True, to="core.attachment"),
        ),
        migrations.AlterField(
            model_name="questionnaireteacher",
            name="surname",
            field=models.CharField(max_length=50, verbose_name="surname"),
        ),
    ]
