# Generated by Django 4.1.4 on 2022-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_questionnaireteacher_certificate_photos_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rate",
            field=models.IntegerField(default=100),
        ),
    ]
