# Generated by Django 4.1.6 on 2023-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_sys_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="background",
            field=models.ImageField(blank=True, upload_to="user_avatars/"),
        ),
    ]
