# Generated by Django 4.1.4 on 2022-12-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_favorites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="favorites",
        ),
    ]
