# Generated by Django 4.1.4 on 2022-12-14 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_user_favorites"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionnaireTeacher",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=30, verbose_name="name")),
                ("surname", models.CharField(max_length=30, verbose_name="surname")),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")],
                        max_length=10,
                        null=True,
                        verbose_name="gender",
                    ),
                ),
                (
                    "about_me",
                    models.CharField(max_length=3000, verbose_name="about my self"),
                ),
                (
                    "work_experience",
                    models.CharField(max_length=1000, verbose_name="work_experience"),
                ),
                (
                    "vk_link",
                    models.CharField(blank=True, max_length=50, verbose_name="vk link"),
                ),
                (
                    "telegram_link",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="telegram link"
                    ),
                ),
                ("certificate_photo", models.ImageField(upload_to="user_certificate/")),
                ("passport_photo", models.ImageField(upload_to="user_passport/")),
                ("user_photo", models.ImageField(upload_to="user_avatars/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета преподавателя",
                "verbose_name_plural": "Анкета преподавателя",
            },
        ),
    ]
