# Generated by Django 4.1.6 on 2023-02-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_register_confirm_code"),
        ("core", "0008_user_background"),
    ]

    operations = []
