# Generated by Django 4.1.6 on 2023-02-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_user_background"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.CharField(choices=[("RU", "Ru")], default="RU", max_length=10),
        ),
    ]
