# Generated by Django 4.1.4 on 2022-12-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_user_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rate",
            field=models.IntegerField(default=5),
        ),
    ]
