# Generated by Django 4.1.4 on 2022-12-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_questionnaireteacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireteacher",
            name="status",
            field=models.CharField(
                choices=[
                    ("MODERATION", "Moderation"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                ],
                default="MODERATION",
                max_length=30,
            ),
        ),
    ]
