# Generated by Django 4.1.6 on 2023-02-09 17:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0010_legaluserbillinginfoeu_legaluserbillinginforu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividualUserBillingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=255)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.RemoveField(
            model_name="legaluserbillinginfo",
            name="user",
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.CharField(
                choices=[("RU", "Ru"), ("EU", "Eu")], default="RU", max_length=10
            ),
        ),
        migrations.CreateModel(
            name="IndividualUserBillingInfoEU",
            fields=[
                (
                    "individualuserbillinginfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.individualuserbillinginfo",
                    ),
                ),
                ("inn", models.CharField(max_length=10, verbose_name="ИНН")),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="Счет"),
                ),
                ("bic", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.individualuserbillinginfo",),
        ),
        migrations.CreateModel(
            name="IndividualUserBillingInfoRU",
            fields=[
                (
                    "individualuserbillinginfo_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.individualuserbillinginfo",
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(regex="^\\d{10}$")
                        ],
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "account_number",
                    models.CharField(max_length=20, verbose_name="Счет"),
                ),
                (
                    "bic",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(regex="^[A-Z0-9]{9}$")
                        ],
                        verbose_name="БИК",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("core.individualuserbillinginfo",),
        ),
    ]
