# Generated by Django 4.1.4 on 2022-12-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_questionnaireteacher_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaireteacher",
            name="telegram_link",
            field=models.URLField(blank=True, verbose_name="telegram link"),
        ),
        migrations.AlterField(
            model_name="questionnaireteacher",
            name="vk_link",
            field=models.URLField(blank=True, verbose_name="vk link"),
        ),
    ]
