# Generated by Django 4.1.6 on 2023-02-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_merge_20230209_1028"),
        ("core", "0011_individualuserbillinginfo_and_more"),
    ]

    operations = []
