# Generated by Django 4.1.6 on 2023-02-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0012_merge_20230209_1803"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherprofiledb",
            name="billing_info_content_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="teacherprofiledb",
            name="billing_info_obj_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
