# Generated by Django 4.1.4 on 2022-12-17 21:37
from typing import List, Any

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_transaction"),
        ("core", "0013_alter_questionnaireteachercertificatephoto_options_and_more"),
    ]

    operations: List[Any] = []
