# Generated by Django 4.1.6 on 2023-02-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_teacherprofiledb_billing_info_content_type_and_more"),
        ("core", "0013_remove_legaluserbillinginfo_bank_and_more"),
    ]

    operations = []
