# Generated by Django 4.1.5 on 2023-02-13 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_merge_20230211_2055"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealSupport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время изменения"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ЖАЛОБА", "Complaint"),
                            ("ПРЕДЛОЖЕНИЕ", "Offer"),
                            ("ЗАЯВЛЕНИЕ", "Statement"),
                        ],
                        max_length=30,
                        verbose_name="Категория",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Тема")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ОТКРЫТА", "Open"),
                            ("В РАССМОТРЕНИИ", "In Process"),
                            ("ОТКЛОНЕНА", "Rejected"),
                            ("ЗАКРЫТА", "Closed"),
                        ],
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения в поддержку",
            },
        ),
    ]
