# Generated by Django 4.1.5 on 2023-02-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_appealsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealSupportCategories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=30, verbose_name="Категория")),
            ],
            options={
                "verbose_name": "категорию",
                "verbose_name_plural": "Категории обращения в поддержку",
            },
        ),
        migrations.AlterModelOptions(
            name="appealsupport",
            options={
                "verbose_name": "обращение",
                "verbose_name_plural": "Обращения в поддержку",
            },
        ),
        migrations.AlterField(
            model_name="appealsupport",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Тема"),
        ),
        migrations.AlterField(
            model_name="appealsupport",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_category",
                to="core.appealsupportcategories",
            ),
        ),
    ]
