# Generated by Django 4.1.4 on 2022-12-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_remove_user_is_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionnaireteacherpassportphoto",
            name="attachment_ptr",
        ),
        migrations.RemoveField(
            model_name="questionnaireteacherpassportphoto",
            name="questionnaire",
        ),
        migrations.RemoveField(
            model_name="questionnaireteacheruserphoto",
            name="attachment_ptr",
        ),
        migrations.RemoveField(
            model_name="questionnaireteacheruserphoto",
            name="questionnaire",
        ),
        migrations.AddField(
            model_name="questionnaireteacher",
            name="certificate_photos",
            field=models.ManyToManyField(to="core.attachment"),
        ),
        migrations.AddField(
            model_name="questionnaireteacher",
            name="passport_photo",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaireteacher",
            name="user_photo",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questionnaireteacher",
            name="user_with_passport_photo",
            field=models.ImageField(default=None, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="questionnaireteacher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="QuestionnaireTeacherCertificatePhoto",
        ),
        migrations.DeleteModel(
            name="QuestionnaireTeacherPassportPhoto",
        ),
        migrations.DeleteModel(
            name="QuestionnaireTeacherUserPhoto",
        ),
    ]
