# Generated by Django 4.1.5 on 2023-02-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_appealsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealSupportCategories",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=30, verbose_name="Категория")),
            ],
        ),
        migrations.AlterField(
            model_name="appealsupport",
            name="category",
            field=models.CharField(max_length=30, verbose_name="Категория"),
        ),
    ]
