# Generated by Django 4.1.5 on 2023-02-14 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_appealsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppealSupportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=30, verbose_name="Категория")),
            ],
            options={
                "verbose_name": "Категория обращения в поддержку",
                "verbose_name_plural": "Категории обращения в поддержку",
            },
        ),
        migrations.AlterModelOptions(
            name="appealsupport",
            options={
                "verbose_name": "Обращение в поддержку",
                "verbose_name_plural": "Обращения в поддержку",
            },
        ),
        migrations.AlterField(
            model_name="appealsupport",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("IN_PROCESS", "In Process"),
                    ("REJECTED", "Rejected"),
                    ("CLOSED", "Closed"),
                ],
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="appealsupport",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Тема"),
        ),
        migrations.AlterField(
            model_name="appealsupport",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.appealsupportcategory",
            ),
        ),
    ]
