# Generated by Django 4.1.5 on 2023-02-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_appealsupportcategories_alter_appealsupport_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appealsupportcategories",
            options={
                "verbose_name": "Категорию",
                "verbose_name_plural": "Категории обращения в поддержку",
            },
        ),
        migrations.AlterField(
            model_name="appealsupport",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Тема"),
        ),
    ]
